version: '3.8'

services:
  chroma:
    image: chromadb/chroma:0.5.23
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped
    networks:
      - techcoach-network

volumes:
  chroma_data:
    driver: local

networks:
  techcoach-network:
    driver: bridge